version: "3.5"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8080:80
    links:
      - fpm
    volumes:
      - ./:/var/www/novs
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    #entrypoint: sh /bin/run.sh
    volumes:
      - ./:/var/www/novs
      - ./scripts/phpEntry.sh:/bin/run.sh
    env_file:
      - '.env'
    depends_on:
      - redis
      - mysql
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: novostroyka_db
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - ./mysqldata:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: novs_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  redis:
    image: redis:4.0
    container_name: app_redis
    ports:
      - "6382:6379"
    volumes:
      - redis:/data

#Volumes
volumes:
  mysqldata:
    driver: local
  redis:
    driver: "local"

networks:
  app-network:
    driver: "bridge"
