version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8080:80
    links:
      - fpm
    depends_on:
      - fpm
      - mysql
    volumes:
      - ./:/var/www/novs
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/novs
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - '.env'
    environment:
      MYSQL_DATABASE: novostroyka_db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin